### ISSUE TITLE
g_currentMission

### ISSUE THREAD

**Issue by theSeb1979** [theSeb1979/FS17_seasons#11]
After much struggling I've finally managed to get a dump out from g_currentMission and it's now part of the project for reference. One thing that is missing from the g_currentMission dump is the functions. Need to try and work on this some more. 

It's not in the friendliest format, but it's workable. 

The first table marked as {1} shows the top level data. 

So if we look down the list we can see, for example, environment. 

`["environment"]={13},`

Now search for {13}

You will find this

```
-- Table: {13}
table: 0x01ccb889c300{
   ["lightTimer"]=4807.3099722862,
   ["nightEnd"]=330,
   ["minRainDuration"]=10800000,
   ["weatherChangeListeners"]={218},
   ["realHourTimer"]=2548060.1929288,
   ["dustGeometry"]=4370,
   ["rainFadeDuration"]=1800000,
   ["water"]=19490,
   ["sunLightId"]=5895,
   ["dayNightCycle"]=true,
   ["needsLights"]=false,
   ["isSunOn"]=true,
   ["currentHour"]=8,
   ["ambientCurve"]={219},
   ["sunHeightAngle"]=-1.221730476396,
   ["autoRain"]=true,
   ["minuteChangeListeners"]={220},
   ["nightStart"]=1260,
   ["sunRotCurve"]={221},
   ["groundWetness"]=0,
   ["dustRootNode"]=4371,
   ["rainForecastDays"]=15,
   ["dayTime"]=30423051.163517,
   ["rainFadeCurve"]={222},
   ["atmosphericRainTypesWeighted"]={223},
   ["timeUpdateTime"]=4810.807071209,
   ["dustDensityCurve"]={224},
   ["timeUpdateInterval"]=60000,
   ["volumeFogCurve"]={225},
   ["lastRainScale"]=0,
   ["rainFogColor"]={226},
   ["minRainInterval"]=345600000,
   ["lastWindFactor"]=0.29657309212685,
   ["maxRainInterval"]=691200000,
   ["maxRainDuration"]=25200000,
   ["currentDay"]=1,
   ["timeSinceLastRain"]=10000105.08018,
   ["skyDayTimeEnd"]=68400000,
   ["weatherTemperaturesNight"]={227},
   ["firstTimeRun"]=true,
   ["weatherForecastDays"]=14,
   ["skyDayTimeStart"]=21600000,
   ["rains"]={228},
   ["allowRain"]=true,
   ["hourChangeListeners"]={229},
   ["rainTypeIdToType"]={230},
   ["rainTypes"]={231},
   ["weatherTemperaturesDay"]={232},
   ["skyId"]=4353,
   ["dayLength"]=86400000,
   ["rainTypesWeighted"]={233},
   ["realHourLength"]=3600000,
   ["currentMinute"]=27,
   ["skyRootId"]=4352,
   ["sunColorCurve"]={234},
   ["realHourChangeListeners"]={235},
   ["dayChangeListeners"]={236},
   ["xmlFilename"]="data/maps/map01_environment.xml",
   ["lightUpdateInterval"]=10000,
   ["skyCurve"]={237},
   ["distanceFogCurve"]={238},
},
```
Quite a few interesting things here, like weatherTemperaturesDay {232} and weatherTemperaturesNight {227}. If you look into {232} you will find this

```
-- Table: {232}
table: 0x01ccb889c300{
   21,
   23,
   25,
   13,
   27,
   19,
   18,
   19,
   24,
   24,
   17,
   23,
   15,
   27,
},
```

In theory we can change those based on the season and it should show up as colder temperatures. However, I am not sure if these temperatures are changing dynamically based on something like weatherChangeListeners. 

Another thing that I've been thinking about is the progression of time. This will be pretty easy because we can dig out the game day, which starts at 1 and increases at midnight (I've tested it)

`self:debugPrint("Current day: " .. g_currentMission.environment.currentDay);`

If we were to say that day 1 = first day of autumn, or summer, or spring, or whatever arbitrary unit of time we agree on, then we can simply check the day as the game is progressing and force crop growth and other variables to do what we want. 

The key thing is to decide what a game day is in real life terms. You mentioned one day to equate to a week. I think that would make things a bit too complex, because some months have different numbers of weeks. I am trying to keep this simple to work out, if possible. In other words, I don't see the need to worry about a time unit as small as a week, because the progression of crops and tasks would not normally change from one week to the next, unless the next week was in the next season. So, I was thinking that perhaps, to keep things simple, 10 days could be a season. Once 10 days have passed, we progress to the next season. This could mean that days 1 to 10 are autumn, 11 to 20 are winter, 21 to 30 are spring, 31 to 40 are summer and 41 to 50 are again autumn. This makes it a lot simpler to work out the season based on the current day. The 10 days per season could be a configurable parameter, so that people can set the season length to whatever they want.

**Comment by theSeb1979** [comment]
We could potentially add early spring, late autumn and so forth as well.

**Comment by joskuijpers** [comment]
10 days a season is annoying because it is not a full week. There is still the notion of monday-sunday, right? Wouldnt it be easier to make a 7 day week (in game) equal a season, or half a season? (two weeks, 14 days, is one season). Then you could make the first 3 days 'early', and the last 3 days 'late'.

**Comment by theSeb1979** [comment]
10 days is just a number I pulled out. It will be configurable for the user to decide how long to make the season via the mod's xml file.

**Comment by ian898** [comment]
I also manged to print g_currentMission but not as well formatted as yours :), 10 seems like a good number but i think it should be down to user to set it later but I did maybe think to suggest setting it lower for testing purposes as 10 days is a long time to sit and wait unless you use fastforward time but that can sometimes cause to miss little errors. (Talking from experience on that one haha)
