### ISSUE TITLE
WF - display weather conditions as an icon

### ISSUE THREAD

**Issue by theSeb1979** [theSeb1979/FS17_seasons#14]
Ideally want to use the game icons in the display to show what is coming up. All of the info is in WeatherForecast.forecast

**Comment by akuenzi** [comment]
Just a thought on this that came to mind.  Weathermen are not perfect.  Maybe you have better ones in teh UK/Europe than we have here, but it's kind of hit and miss.  They are 'generally' correct, but never perfect.  **Should the weather report being built incorporate a margin of error into it, so as to simulate real weathermen?**  Should it sometimes be flat-out wrong (ie, predicting sunshine, and rain comes instead)?

**Comment by ian898** [comment]
I like the idea but here in UK it is more than hit and miss I find there never right really but considering it rains 80% of the year lol you would think they would at least be 80% right haha

**Comment by joskuijpers** [comment]
Nah.

If it rains for 1 day in the game, that is like a week in real life. They don’t miss that.

**Comment by theSeb1979** [comment]
Not relevant for now. Closing this based on https://github.com/theSeb1979/FS17_seasons/issues/12
