### ISSUE TITLE
Class prefixes

### ISSUE THREAD

**Issue by joskuijpers** [theSeb1979/FS17_seasons#29]
Maybe we should be using prefixes so that classes will nog collide with other mods.

Something like: ssTime, (ss = SeasonS), ssWeatherForecast. Also name the files this.

**Comment by theSeb1979** [comment]
Good call. I was thinking about this when I started writing the code, but could not come up with a witty prefix. I suppose ss will work.

**Comment by joskuijpers** [comment]
Ill refactor all the things and clean up the repo.

**Comment by theSeb1979** [comment]
Cool.
