### ISSUE TITLE
Team name

### ISSUE THREAD

**Issue by joskuijpers** [theSeb1979/FS17_seasons#32]
Should we have a team name? :p

**Comment by theSeb1979** [comment]
I don't mind, as long as it's witty and original. :D

**Comment by ian898** [comment]
@theSeb1979 

I second that haha

**Comment by joskuijpers** [comment]
Quickly! :P I will make a slack group (so download Slack) so we can talk. Need a name though

**Comment by joskuijpers** [comment]
Realismod xD not witty

**Comment by joskuijpers** [comment]
Could do DrRealismod :P I dunno

**Comment by joskuijpers** [comment]
Realismus Modding, as slack is now?
